// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgsaazntnhtbrwchvnxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhnc2Fhem50bmh0YnJ3Y2h2bnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTU3MDAsImV4cCI6MjA1ODQ5MTcwMH0.GP1QMFgNN2uKM3LVqPbkQk5PSL-phJ0Iqx96AFAQyqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);